### ISSUE TITLE
SIPDump fails build in 615fbe9ac

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#578]
```
gcc SIPdump.o memdbg.o -m64 -g  -L/usr/local/lib -L/usr/local/ssl/lib  -lmpi -lpthread -lrexgen -ldl -lgmp -lkrb5 -lk5crypto -lz -lm -lcrypto -lssl -lpcap  -fopenmp -DHAVE_MPI -L/usr/local/cuda/lib -Wl,-framework,OpenCL  -o ../run/SIPdump
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[1]: *** [../run/SIPdump] Error 1
```
