### PR TITLE
 Updated office2john.py for Python 3.10+ 

### LINKED ISSUE #5371: office2john fails on python 3.10+
### Checklist ###
- :1st_place_medal: I've read and understood these instructions;
  - This is not a support forum, it's a bug tracker. For questions and support, review postings on the [john-users mailing list](https://www.openwall.com/lists/john-users/).
- :thumbsup: I've tested using latest bleeding version from this repository.
  - Be clear about your environment and what you are doing. Share a sample hash or file that can be used to reproduce.
- :confused: I'm confused and I need guidance.
  - Please, read the instructions at https://www.openwall.com/john/#lists, then join the list before posting.

### IMPORTANT ###
We expect only reports of issues with the latest revision found in this GitHub repository. We do not expect in here, and have little use for, reports of issues only seen in a release or in a distro package.

Attach details about your OS and about john, including:
<details> 
  <summary>The output of `./john --list=build-info`. </summary>
```

Version: 1.9.0-jumbo-1
Build: linux-gnu 64-bit x86_64 AVX AC MPI + OMP
SIMD: AVX, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
System-wide exec: /usr/lib/john
System-wide home: /usr/share/john
Private home: ~/.john
CPU tests: AVX
CPU fallback binary: john-non-avx
$JOHN is /usr/share/john/
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 2147483648
SINGLE_BUF_MAX: 4294967295
Effective limit: Number of salts vs. SingleMaxBufferSize
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 13.2.1
GNU libc version: 2.38 (loaded: 2.38)
OpenCL headers version: 1.2
Crypto library: OpenSSL
OpenSSL library version: 030100020	(loaded: 030100040)
OpenSSL 3.1.2 1 Aug 2023	(loaded: OpenSSL 3.1.4 24 Oct 2023)
GMP library version: 6.3.0
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's ```


</details>

<details> 
  <summary>The command line you are using. </summary>
`./office2john ./N.docx > hash_N`
</details>

<details> 
  <summary>Traceback</summary>

Traceback (most recent call last):
  File "/usr/bin/office2john", line 3082, in <module>
    ret = process_file(sys.argv[i])
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/office2john", line 3005, in process_file
    return process_new_office(filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/office2john", line 2813, in process_new_office
    xml_metadata_parser(data, filename)
  File "/usr/bin/office2john", line 2857, in xml_metadata_parser
    for node in tree.getiterator('{http://schemas.microsoft.com/office/2006/keyEncryptor/password}encryptedKey'):
                ^^^^^^^^^^^^^^^^
AttributeError: 'ElementTree' object has no attribute 'getiterator'
</details>

`getiterator` method was depreciated in Python 3.9, so it would not work with newer versions

### PR DESCRIPTION
**Pull request by nastyagrifon**
methods `getiterator` and `base64.decodestring` are depreciated and must be replaced. The suggested methods work on Python 3.9 , 3.10 and 3.11. Haven't tested other versions.

Closes #5371

### CODE REVIEW

**Comment by ghost** [comment]
Thanks for contributing,

Unfortunately, I'm afraid this patch is wrong. You are facing a problem on Jumbo 1, but you have proposed a fix for bleeding code.

Reading the committed code in this repo you may notice that a fix has already been merged.. E.g., at https://github.com/openwall/john/commit/eb7cbf6e72ba4ad04a164fe832de51b59e94b6f9

The same applies to `decodestring`
****

Please try the latest committed code and report back if you still find any issues.

**Comment by nastyagrifon** [comment]
> Thanks for contributing,
> 
> Unfortunately, I'm afraid this patch is wrong. You are facing a problem on Jumbo 1, but you have proposed a fix for bleeding code.
> 
> Reading the committed code in this repo you may notice that a fix has already been merged.. E.g., at [eb7cbf6](https://github.com/openwall/john/commit/eb7cbf6e72ba4ad04a164fe832de51b59e94b6f9)
> 
> The same applies to `decodestring`
> 
> Please try the latest committed code and report back if you still find any issues.

my bad
