### ISSUE TITLE
Build with OpenSSL 1.1.1d on macOS fails

### ISSUE THREAD

**Issue by fxcoudert** [openwall/john#4099]
### Steps to reproduce ###

- download JohnTheRipper-1.9.0-Jumbo-1
- `./configure --disable-native-tests OPENSSL_CFLAGS=-I/usr/local/opt/openssl@1.1/include OPENSSL_LIBS='-L/usr/local/opt/openssl\@1.1/lib -lssl -lcrypto'`
- `make`

This gives the following errors:

```
gpg_common_plug.c:1086:29: error: incomplete definition of type 'struct dsa_st'
        error = BN_mod_exp(res, dsa->g, dsa->priv_key, dsa->p, ctx);
                                ~~~^
/usr/local/opt/openssl@1.1/include/openssl/ossl_typ.h:107:16: note: forward declaration of 'struct dsa_st'
typedef struct dsa_st DSA;
               ^
gpg_common_plug.c:1086:37: error: incomplete definition of type 'struct dsa_st'
        error = BN_mod_exp(res, dsa->g, dsa->priv_key, dsa->p, ctx);
                                        ~~~^
/usr/local/opt/openssl@1.1/include/openssl/ossl_typ.h:107:16: note: forward declaration of 'struct dsa_st'
typedef struct dsa_st DSA;
               ^
gpg_common_plug.c:1086:52: error: incomplete definition of type 'struct dsa_st'
        error = BN_mod_exp(res, dsa->g, dsa->priv_key, dsa->p, ctx);
                                                       ~~~^
/usr/local/opt/openssl@1.1/include/openssl/ossl_typ.h:107:16: note: forward declaration of 'struct dsa_st'
typedef struct dsa_st DSA;
               ^
gpg_common_plug.c:1096:22: error: incomplete definition of type 'struct dsa_st'
        rc = BN_cmp(res, dsa->pub_key);
                         ~~~^
/usr/local/opt/openssl@1.1/include/openssl/ossl_typ.h:107:16: note: forward declaration of 'struct dsa_st'
typedef struct dsa_st DSA;
               ^
gpg_common_plug.c:1104:13: error: incomplete definition of type 'struct dsa_st'
        BN_free(dsa->g);
                ~~~^
/usr/local/opt/openssl@1.1/include/openssl/ossl_typ.h:107:16: note: forward declaration of 'struct dsa_st'
typedef struct dsa_st DSA;
               ^
gpg_common_plug.c:1105:13: error: incomplete definition of type 'struct dsa_st'
        BN_free(dsa->q);
                ~~~^
/usr/local/opt/openssl@1.1/include/openssl/ossl_typ.h:107:16: note: forward declaration of 'struct dsa_st'
typedef struct dsa_st DSA;
               ^
gpg_common_plug.c:1106:13: error: incomplete definition of type 'struct dsa_st'
        BN_free(dsa->p);
                ~~~^
/usr/local/opt/openssl@1.1/include/openssl/ossl_typ.h:107:16: note: forward declaration of 'struct dsa_st'
typedef struct dsa_st DSA;
               ^
gpg_common_plug.c:1107:13: error: incomplete definition of type 'struct dsa_st'
        BN_free(dsa->pub_key);
                ~~~^
/usr/local/opt/openssl@1.1/include/openssl/ossl_typ.h:107:16: note: forward declaration of 'struct dsa_st'
typedef struct dsa_st DSA;
               ^
gpg_common_plug.c:1108:13: error: incomplete definition of type 'struct dsa_st'
        BN_free(dsa->priv_key);
                ~~~^
/usr/local/opt/openssl@1.1/include/openssl/ossl_typ.h:107:16: note: forward declaration of 'struct dsa_st'
typedef struct dsa_st DSA;
               ^
gpg_common_plug.c:1595:9: error: variable has incomplete type 'DSA' (aka 'struct dsa_st')
                                DSA dsa;
                                    ^
/usr/local/opt/openssl@1.1/include/openssl/ossl_typ.h:107:16: note: forward declaration of 'struct dsa_st'
typedef struct dsa_st DSA;
               ^
```

because in `gpg_common_plug.c` it's not following the `HAVE_DSA_GET0_PQG` codepaths (which it should). This is because:

```
#if !AC_BUILT && OPENSSL_VERSION_NUMBER >= 0x10100000
#define HAVE_DSA_GET0_PQG 1
#endif
```

Apparently `AC_BUILT` means “building with autoconf”, which is true in my case. **The remaining mystery is why building with autoconf is meant to override the detection of OpenSSL version number**

### Fix ###

I can confirm that changing the above code to:

```
#if OPENSSL_VERSION_NUMBER >= 0x10100000
#define HAVE_DSA_GET0_PQG 1
#endif
```

allows the build to complete successfully.

### System configuration ###

macOS 10.13, with system tools (Xcode, clang) and gmp provided by Homebrew. OpenSSL 1.1.1d is provided by Homebrew also. Disabling OpenSSL also fails: https://github.com/magnumripper/JohnTheRipper/issues/4098

**Comment by magnumripper** [comment]
OpenSSL have a habit of dropping stuff, sometimes with NO version between "deprecated" and "dropped" 😢 

Again, my firm opinion is that #3998 is the way to go.

**Comment by fxcoudert** [comment]
> OpenSSL have a habit of dropping stuff

I don't think that's the issue here at all, as the necessary code (depending on `OPENSSL_VERSION_NUMBER`) was already put in place. It's just guarded by the wrong condition, I think.

**Comment by magnumripper** [comment]
Sorry for not reading carefully (I still want to drop OpenSSL 😎). So what you are saying is that somehow the `!AC_BUILT && ` disturbs it? I guess that means we have an autoconf test that is supposed to define `HAVE_DSA_GET0_PQG` from some "real" test that we might have gotten wrong. I'll have a look at it - thanks!

**Comment by fxcoudert** [comment]
Ok I see the test for `DSA_get0_pqg` in `configure.ac`. I can confirm that it is not well detected. This is apparently because even though I configure with

```
./configure --disable-native-tests OPENSSL_CFLAGS=-I/usr/local/opt/openssl@1.1/include OPENSSL_LIBS='-L/usr/local/opt/openssl\@1.1/lib -lssl -lcrypto'
```

the `OPENSSL_LIBS` is not used when testing for `DSA_get0_pqg`:

```
configure:13213: checking for DSA_get0_pqg
configure:13213: gcc -o conftest -I/usr/local/opt/openssl@1.1/include -m64 -g -O2 -I/usr/local/include -I/usr/local/opt/openssl@1.1/include  -I/usr/local/include -m64  -L/usr/local/lib conftest.c -lssl -lcrypto   >&5
Undefined symbols for architecture x86_64:
  "_DSA_get0_pqg", referenced from:
      _main in conftest-1fe55e.o
```

This is because earlier, it appears my `OPENSSL_LIBS` settings is actually being overrode. I couldn't figure out why, though :(

**Comment by catap** [comment]
Fixed by https://github.com/magnumripper/JohnTheRipper/pull/4101

**Comment by ghost** [comment]
It seems some detail is still missing.

`./configure OPENSSL_CFLAGS=-I/usr/local/opt/openssl@1.1/include OPENSSL_LIBS='-L/usr/local/opt/openssl\@1.1/lib -lssl -lcrypto'`
```
checking supplied paths for OpenSSL... -I/usr/local/opt/openssl@1.1/include -L/usr/local/opt/openssl\@1.1/lib -lssl -lcrypto
checking additional paths for OpenSSL... none
checking openssl/opensslv.h usability... yes
checking openssl/opensslv.h presence... no
configure: WARNING: openssl/opensslv.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: openssl/opensslv.h: proceeding with the compiler's result
checking for openssl/opensslv.h... yes
checking for SSL_CTX_new in -lssl... no
configure: error: in `/Users/travis/build/claudioandre-br/JohnTheRipper/src':
configure: error: JtR requires libssl being installed
```
*****

Travis updated its OSX image recently. It is failing since.

A regular `./configure`:
```
checking for openssl/opensslv.h... no
configure: error: in `/Users/travis/build/claudioandre-br/JohnTheRipper/src':
configure: error: JtR requires OpenSSL headers being installed
```

**Comment by catap** [comment]
@claudioandre-br it is very strange. Because I've created a few patches to fix this issue and this is similar to that I've fixed.

Do you using the last master?

**Comment by ghost** [comment]
> 
> Do you using the last master?

Yes

**Comment by ghost** [comment]
To see all source files used for build: 
* https://github.com/claudioandre-br/JohnTheRipper/tree/8af991fd5bd24f2aff4c707ebd4a48824b94476d

Logs, including config.log (**cloud sync still running**)
* xcode11.2: https://api.travis-ci.org/v3/job/608781779/log.txt
* xcode10.2: https://api.travis-ci.org/v3/job/608781780/log.txt

**Comment by magnumripper** [comment]
Closing bc wo

**Comment by dsxack** [comment]
@claudioandre-br at me it was because duplicated libs was at `/usr/local/opt` from previous HomeBrew installation after I migrated from x86_64 mac to m1 (now libs located at `/opt/homebrew`). 

So I deleted previous HomeBrew installation with `PATH=/usr/local/bin:$PATH arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"` and now john compiled good with `./configure OPENSSL_CFLAGS='-I/opt/homebrew/opt/openssl@1.1/include' OPENSSL_LIBS='-L/opt/homebrew/opt/openssl@1.1/lib -lssl -lcrypto'`

**Comment by ghost** [comment]
I'm afraid I can't understand what's wrong now. (for me) It works on M1 and on X86 nowadays.

**Comment by dsxack** [comment]
@claudioandre-br It works for me now too, I just wrote if the problem was not resolved
